name: CI Pipeline

on:
  pull_request:
    branches: [main, master]
  push:
    branches: [main, master]

jobs:
  lint:
    name: Линтинг с Ruff
    runs-on: ubuntu-latest
    steps:
      - name: Проверка кода
        uses: actions/checkout@v4

      - name: Настройка Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Установка Ruff
        run: pip install ruff==0.14.6

      - name: Запуск Ruff проверки
        run: ruff check --output-format=github

  test:
    name: Запуск модульных тестов
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Проверка кода
        uses: actions/checkout@v4

      - name: Настройка Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Установка зависимостей
        run: pip install -r requirements.txt

      - name: Запуск тестов
        run: |
          pip install -e .
          python -m pytest test_class_car.py -v

